services:
  web:
    restart: "always"
    build: "."
    ports:
      - "5000:5000"
    volumes:
      - "./app:/home/fall_risk_db/app"
      - "./migrations:/home/fall_risk_db/migrations"
    depends_on:
      - "db"
  db:
    image: "postgres:bullseye"
    environment:
      - "POSTGRES_DB=fall_risk_db"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=password"
    volumes:
      - "./postgresql-data:/var/lib/postgresql/data"
